apiVersion: gateway.envoyproxy.io/v1alpha1
kind: ClientTrafficPolicy
metadata:
  name: client-ip-detection
  namespace: envoy-gateway
spec:
  targetRef:
    - group: gateway.networking.k8s.io
      kind: Gateway
      name: lnetcore
  clientIPDetection:
    xForwardedFor:
      numTrustedHops: 1
  headers:
    earlyRequestHeaders:
      add:
        - name: x-forwarded-for
          value: "%DOWNSTREAM_REMOTE_ADDRESS_WITHOUT_PORT%"
        - name: x-real-ip
          value: "%DOWNSTREAM_REMOTE_ADDRESS_WITHOUT_PORT%"
