# ReferenceGrant lmonitor to lnetcore
apiVersion: gateway.networking.k8s.io/v1beta1
kind: ReferenceGrant
metadata:
  name: refgrant-lnetcore
  namespace: lmonitor
spec:
  from:
  - group: gateway.networking.k8s.io
    kind: HTTPRoute
    namespace: lnetcore
  to:
  - group: ""
    kind: Service

---
# ReferenceGrant ldevops to lnetcore
apiVersion: gateway.networking.k8s.io/v1beta1
kind: ReferenceGrant
metadata:
  name: refgrant-lnetcore
  namespace: ldevops
spec:
  from:
  - group: gateway.networking.k8s.io
    kind: HTTPRoute
    namespace: lnetcore
  to:
  - group: ""
    kind: Service

