# Authentik Outpost
apiVersion: goauthentik.io/v1alpha1
kind: Outpost
metadata:
  name: authentik-outpose
  namespace: lcntwk
spec:
  type: proxy

  kubernetes:
    enabled: true
    httproute_parent_refs:
    - name: default-gateway
      namespace: lcntwk
  protocol: http
  service:
    url: http://authentik-server.lcntwk.svc.cluster.local:9000

  
---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: private-httproute
  namespace: lcntwk
spec:
  parentRefs:
  - name: default-gateway
    kind: Gateway
  hostnames:
  - admin.lilamaris.kr
  rules:
  - matches:
    - path:
        type: PathPrefix
        value: /monitor
    backendRefs:
      - name: prometheus-grafana
        namespace: lcmntr
        port: 80

