# HTTP Route for admin.lilamaris.kr
# sub-path list
#   root: Not Found
#   /monitor: prometheus-grafana.lcmntr.svc.cluster.local:80 - kube-prometheus-grafana stacks ui dashboard
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: admin
  namespace: lnetcore
spec:
  parentRefs:
  - name: default-gateway
    kind: Gateway
  hostnames:
  - admin.lilamaris.kr
  rules:
  - matches:
    - path:
        type: PathPrefix
        value: /monitor
    backendRefs:
      - name: prometheus-grafana
        namespace: lcmntr
        port: 80

---

