# Authentik Outpost
apiVersion: goauthentik.io/v1alpha1
kind: Outpost
metadata:
  name: authentik-outpose
  namespace: lnetstack
spec:
  type: proxy

  kubernetes:
    enabled: true
    httproute_parent_refs:
    - name: default-gateway
      namespace: lnetcore
  protocol: http
  service:
    url: http://authentik-server.lcntwk.svc.cluster.local:9000

---

