apiVersion: v1
kind: Namespace
metadata:
  name: lnetstack
  labels:
    role: lnetstack
  annotations:
    description: >
      Networking integration namespace.
      Hosts services that sit atop the network layer:
        - Proxy workload (e.g., Envoy, Nginx)
        - Bot detection and WAF (e.g., fail2ban, ModSecurity, Anubis)
        - API Gateway, OAuth2-proxy, Authentik
        
