# HTTP Route for git.lilamaris.kr
# sub-path list
#   root: gitea-http.ldevops.svc.cluster.local:3000 - gitea version control web application
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: git
  namespace: lnetcore
spec:
  parentRefs:
  - name: public-gateway
    kind: Gateway
    sectionName: https
  hostnames:
  - git.lilamaris.kr
  rules:
  - matches:
    - path:
        type: PathPrefix
        value: /
    backendRefs:
      - name: anubis
        namespace: ldevops
        port: 8080
---
# TCP Route for git.lilamaris.kr
apiVersion: gateway.networking.k8s.io/v1alpha2
kind: TCPRoute
metadata:
  name: git-ssh
  namespace: lnetcore
spec:
  parentRefs:
  - name: public-gateway
    kind: Gateway
    sectionName: ssh
  rules:
    - backendRefs:
        - name: gitea-ssh
          namespace: ldevops
          port: 22
