apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: n8n-db
  namespace: lautomation
spec:
  instances: 2
  storage:
    size: 10Gi
    storageClass: cnpg-local-path
  bootstrap:
    initdb:
      database: n8n
      owner: n8n
