apiVersion: apps/v1
kind: Deployment
metadata:
  name: n8n
  namespace: lautomation
  labels:
    app: n8n
spec:
  replicas: 1
  selector:
    matchLabels:
      app: n8n
  template:
    metadata:
      labels:
        app: n8n
    spec:
      containers:
      - name: n8n
        image: n8nio/n8n:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 5678
        env:
        - name: DB_POSTGRESDB_HOST
          valueFrom: { secretKeyRef: { name: n8n-db-app, key: host } }
        - name: DB_POSTGRESDB_PORT
          valueFrom: { secretKeyRef: { name: n8n-db-app, key: port } }
        - name: DB_POSTGRESDB_DATABASE
          valueFrom: { secretKeyRef: { name: n8n-db-app, key: dbname } }
        - name: DB_POSTGRESDB_USER
          valueFrom: { secretKeyRef: { name: n8n-db-app, key: username } }
        - name: DB_POSTGRESDB_PASSWORD
          valueFrom: { secretKeyRef: { name: n8n-db-app, key: password } }
        envFrom:
        - configMapRef:
            name: n8n-configmap
        volumeMounts:
        - name: data
          mountPath: /home/node/.n8n
      volumes:
      - name: data
        persistentVolumeClaim:
          claimName: n8n-data
