apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: n8n-data
  namespace: lautomation
spec:
  accessModes: ["ReadWriteOnce"]
  resources:
    requests:
      storage: 10Gi
  storageClassName: cnpg-local-path
