# Certificate for wildcard
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: lilamaris-wildcard-cert
  namespace: kube-system
spec:
  dnsNames:
  - lilamaris.kr
  - '*.lilamaris.kr'
  issuerRef:
    name: lilamaris-issuer
    kind: ClusterIssuer
  secretName: lilamaris-wildcard-tls
  secretTemplate:
    annotations:
      reflector.v1.k8s.emberstack.com/reflection-allowed: "true"
      reflector.v1.k8s.emberstack.com/reflection-allowed-namespaces: ""
      reflector.v1.k8s.emberstack.com/reflection-auto-enabled: "true"
      reflector.v1.k8s.emberstack.com/reflection-auto-namespaces: "lnetcore,lnetstack"

